name: ğŸš€ Deploy Logix Hrm on Development server

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2

    # - name: ğŸ˜ Install Composer Dependencies
    #   run: composer install --prefer-dist --no-progress --no-suggest

    # - name: ğŸ˜ Run Database Migrations
    #   run: php artisan migrate

    # Deploy files via FTP
    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # ğŸ‘‡ This is the remote folder you want to deploy into
        #server-dir: /api.upliffting.com/
        exclude: |
          vendor/*
          public/*
        clean: false
        force: false
        verbose: true